config/routes.rb
Rails.application.routes.draw do
  root 'landing#index'
  devise_for :users

  namespace :api do
    resources :galleries, only: [:index, :show]
    resources :writings, only: [:show]
  end

  namespace :admin do
    resources :galleries
    resources :writings
  end

  get 'galleries/*gallery', to: 'landing#index'
  get '*all', to: 'landing#index'
end

app/models/content_converter.rb
class ContentConverter
  def self.to_json(text)
    if text.strip[0] != "#"
      return JSON.generate([])
    end

    content_array = []
    paragraphs = text.split(/\n/).map(&:strip).select(&:presence)

    paragraphs.each do |paragraph|
      if paragraph[0] == "#"
        current_section = {}
        content_array << current_section
        current_section[:header] = paragraph[1..-1]
        current_section[:paragraphs] = []
      else
        current_section = content_array[-1]
        current_section[:paragraphs] << paragraph
      end
    end

    JSON.generate(content_array)
  end

  def self.to_text(json)
    JSON.parse(json).reduce("") do |text, hash|
      text += "#" + hash["header"] + "\n"

      if hash["paragraphs"].any?
        text += hash["paragraphs"].join("\n") + "\n"
      end

      text
    end
  end

  def self.to_html(json)
    JSON.parse(json).reduce("") do |text, hash|
      text += "<h1>" + hash["header"] + "</h1>"
      text += hash["paragraphs"].map { |p| "<p>#{p}</p>" }.join("")
    end
  end
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  validates :permalink, :title, :snippet, :flickr_id, presence: true
  validates :permalink, uniqueness: true
  validates :category, inclusion: { in: ["painting", "photo"] }

  def pictures
    @pictures ||= []
  end

  def pictures=(pictures)
    @pictures = pictures
  end
end

app/models/picture.rb
class Picture
  attr_reader :id, :title, :description, :small_url, :small_width, :small_height, :medium_url, :medium_width, :medium_height, :original_url, :original_width, :original_height

  def self.from_flickr(hash)
    new(
      id: hash["id"],
      title: hash["title"],
      description: hash["description"],
      small_url: hash["url_s"],
      small_width: hash["width_s"],
      small_height: hash["height_s"],
      medium_url: hash["url_m"],
      medium_width: hash["width_m"],
      medium_height: hash["height_m"],
      original_url: hash["url_o"],
      original_width: hash["width_o"],
      original_height: hash["height_o"]
    )
  end

  def initialize(attrs = {})
    attrs.each do |attr, value|
      instance_variable_set("@#{attr}", value)
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/writing.rb
class Writing < ActiveRecord::Base
  attr_reader :editable_content

  def editable_content=(text)
    self.content = ContentConverter.to_json(text)
  end

  def editable_content
    ContentConverter.to_text(content)
  end

  def html_content
    ContentConverter.to_html(content)
  end

  private

  def content=(val)
    write_attribute :content, val
  end
end

app/controllers/admin/galleries_controller.rb
class Admin::GalleriesController < ApplicationController
  layout "admin/application"

  before_action :authorize_admin
  before_action :set_gallery, only: [:show, :edit, :update, :destroy]

  # GET /galleries
  # GET /galleries.json
  def index
    @galleries = Gallery.all
  end

  # GET /galleries/1
  # GET /galleries/1.json
  def show
  end

  # GET /galleries/new
  def new
    @gallery = Gallery.new
  end

  # GET /galleries/1/edit
  def edit
  end

  # POST /galleries
  # POST /galleries.json
  def create
    @gallery = Gallery.new(gallery_params)

    respond_to do |format|
      if @gallery.save
        format.html { redirect_to edit_admin_gallery_path(@gallery), notice: 'Gallery was successfully created.' }
        format.json { render :show, status: :created, location: @gallery }
      else
        format.html { render :new }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /galleries/1
  # PATCH/PUT /galleries/1.json
  def update
    respond_to do |format|
      if @gallery.update(gallery_params)
        format.html { redirect_to edit_admin_gallery_path(@gallery), notice: 'Gallery was successfully updated.' }
        format.json { render :show, status: :ok, location: @gallery }
      else
        format.html { render :edit }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galleries/1
  # DELETE /galleries/1.json
  def destroy
    @gallery.destroy
    respond_to do |format|
      format.html { redirect_to admin_galleries_url, notice: 'Gallery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gallery
      @gallery = Gallery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gallery_params
      params.require(:gallery).permit(:permalink, :flickr_id, :title, :snippet, :explanation)
    end
end

app/controllers/admin/writings_controller.rb
class Admin::WritingsController < ApplicationController
  layout "admin/application"

  before_action :authorize_admin

  def index
    @writings = Writing.all
  end

  def edit
    @writing = Writing.find(params[:id])
  end

  def update
    @writing = Writing.find(params[:id])
    @writing.update_attributes(writing_params)
  end

  def new
    @writing = Writing.new
  end

  def create
    @writing = Writing.create(writing_params)
  end

  private

  def writing_params
    params.require(:writing).permit(:permalink, :editable_content)
  end
end

app/controllers/api/galleries_controller.rb
module Api
  class GalleriesController < ApplicationController
    layout false
    respond_to :json

    def index
      @galleries = GalleryService.get_all
    end

    def show
      @gallery = GalleryService.get(params[:id])
    end
  end
end

app/controllers/api/writings_controller.rb
module Api
  class WritingsController < ApplicationController
    layout false
    respond_to :json

    def show
      @writing = Writing.find_by(permalink: params[:id])
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout :layout_by_resource

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def admin?
    current_user && current_user.email == "jonashart@gmail.com"
  end

  def authorize_admin
    if !admin?
      redirect_to new_user_session_path
    end
  end

  def after_sign_in_path_for(resource)
    admin_galleries_path
  end

  protected

  def layout_by_resource
    if devise_controller?
      "admin/application"
    else
      "application"
    end
  end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/views/admin/galleries/_form.html.slim
= form_for [:admin, @gallery] do |f|
  - if @gallery.errors.any?
    #error_explanation
      h2 = "#{pluralize(@gallery.errors.count, "error")} prohibited this gallery from being saved:"
      ul
        - @gallery.errors.full_messages.each do |message|
          li = message
          
  - if flash[:notice].present?
    .success-notice = flash[:notice]

  .field
    = f.label :permalink
    = f.text_field :permalink
  .field
    = f.label :flickr_id
    = f.text_field :flickr_id
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :snippet
    = f.text_area :snippet
  .field
    = f.label :explanation
    = f.text_area :explanation
    
  .actions = f.submit

app/views/admin/galleries/edit.html.slim
h1 Editing gallery

== render 'form'

= link_to 'Back', admin_galleries_path

app/views/admin/galleries/index.html.slim
h1 Listing galleries

table
  thead
    tr
      th Permalink
      th
      th
      th

  tbody
    - @galleries.each do |gallery|
      tr
        td = gallery.permalink
        td = link_to 'Edit', edit_admin_gallery_path(gallery)
        td = link_to 'Destroy', [:admin, gallery], data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Gallery', new_admin_gallery_path

app/views/admin/galleries/new.html.slim
h1 New gallery

== render 'form'

= link_to 'Back', admin_galleries_path

app/views/admin/writings/edit.html.slim
= form_for [:admin, @writing], html: { class: "writing-form" } do |f|
  div = f.object.permalink
  = f.text_area :editable_content

  = f.submit

app/views/admin/writings/index.html.slim
.writings-list
  - @writings.each do |writing|
    .writings-list__item
      .writings-list__item-name = writing.permalink
      = link_to "edit", edit_admin_writing_path(writing), class: "writings-list__item-action"

app/views/admin/writings/new.html.slim
h1 Admin::Writings#new
p Find me in app/views/admin/writings/new.html.slim

app/views/layouts/admin/application.slim
doctype html
html
  head
    title Jonas Art Admin
    = csrf_meta_tags
    = stylesheet_link_tag "admin_application"

  body
    nav.nav-bar
      - if current_user
        = button_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-bar__item"
      = link_to "galleries", admin_galleries_path, class: "nav-bar__item"
      = link_to "writings", admin_writings_path, class: "nav-bar__item"
    = yield

app/views/layouts/application.slim
doctype html
html
  head
    title Jonas Art
    = csrf_meta_tags
    meta name="viewport" content="width=device-width, initial-scale=1"

  body
    #app-content
      = yield

    = javascript_include_tag 'application'
    = stylesheet_link_tag 'application'